"""empty message

Revision ID: 50029077e9a6
Revises: 
Create Date: 2021-08-06 20:51:08.970667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50029077e9a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('UserName', sa.String(), nullable=False),
    sa.Column('UserEmail', sa.String(), nullable=False),
    sa.Column('UserGender', sa.String(), nullable=False),
    sa.Column('UserAge', sa.String(), nullable=True),
    sa.Column('Location', sa.String(), nullable=True),
    sa.Column('UserJob', sa.String(), nullable=True),
    sa.Column('About', sa.String(), nullable=True),
    sa.Column('UserPriority', sa.String(), nullable=True),
    sa.Column('UserPassword', sa.String(), nullable=False),
    sa.Column('UserImageLink', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('UserID')
    )
    op.create_table('chats',
    sa.Column('ChatID', sa.Integer(), nullable=False),
    sa.Column('SenderID', sa.Integer(), nullable=True),
    sa.Column('ReceiverID', sa.Integer(), nullable=True),
    sa.Column('Read_Unread', sa.Boolean(), nullable=False),
    sa.Column('Deleted', sa.Boolean(), nullable=False),
    sa.Column('Deleted_By', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ReceiverID'], ['user.UserID'], ),
    sa.ForeignKeyConstraint(['SenderID'], ['user.UserID'], ),
    sa.PrimaryKeyConstraint('ChatID')
    )
    op.create_table('matches',
    sa.Column('MatchID', sa.Integer(), nullable=False),
    sa.Column('ReceiverID', sa.Integer(), nullable=False),
    sa.Column('Connected', sa.Boolean(), nullable=True),
    sa.Column('User_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['User_id'], ['user.UserID'], ),
    sa.PrimaryKeyConstraint('MatchID')
    )
    op.create_table('messages',
    sa.Column('MessageID', sa.Integer(), nullable=False),
    sa.Column('ReceiverID', sa.Integer(), nullable=False),
    sa.Column('Message', sa.String(), nullable=False),
    sa.Column('TimeSent', sa.DateTime(), nullable=False),
    sa.Column('DeleteForEveryone', sa.Boolean(), nullable=True),
    sa.Column('UserID', sa.Integer(), nullable=True),
    sa.Column('ChatID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ChatID'], ['chats.ChatID'], ),
    sa.ForeignKeyConstraint(['UserID'], ['user.UserID'], ),
    sa.PrimaryKeyConstraint('MessageID')
    )
    op.create_table('deleteforme',
    sa.Column('UserID', sa.Integer(), nullable=True),
    sa.Column('MessageID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['MessageID'], ['messages.MessageID'], ),
    sa.ForeignKeyConstraint(['UserID'], ['user.UserID'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deleteforme')
    op.drop_table('messages')
    op.drop_table('matches')
    op.drop_table('chats')
    op.drop_table('user')
    # ### end Alembic commands ###
